replicaCount: 1

image:
  repository: 758024567313.dkr.ecr.ap-south-1.amazonaws.com/backend-api-dev
  pullPolicy: IfNotPresent
  tag: e9d80b8e9bb29323c3f0e785ccf04f09469f83d9

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: shared-alb
  paths:
    - path: /dev
      pathType: Prefix

env:
  - name: APP_ENV
    value: "dev"

livenessProbe:
  httpGet:
    path: /dev/health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /dev/health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

resources: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
