apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: dev
type: Opaque
stringData:
  DB_HOST: your-rds-endpoint.amazonaws.com
  DB_NAME: appdb
  DB_USER: admin
  DB_PASSWORD: password123