apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: dev
type: Opaque
stringData:
  DB_HOST: platform-mysql-new.cvi2swcoup2y.ap-south-1.rds.amazonaws.com
  DB_NAME: platform
  DB_USER: admin
  DB_PASSWORD: StrongPassword123!