name: Database Migration Dev

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::758024567313:role/github-oidc-role
        aws-region: ap-south-1

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name demo-eks --region ap-south-1

    - name: Apply dev secret and configmap
      run: |
        kubectl create namespace dev --dry-run=client -o yaml | kubectl apply -f -
        kubectl create secret generic rds-secret -n dev \
          --from-literal=DB_HOST=${{ secrets.DEV_DB_HOST }} \
          --from-literal=DB_NAME=${{ secrets.DEV_DB_NAME }} \
          --from-literal=DB_USER=${{ secrets.DEV_DB_USER }} \
          --from-literal=DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }} \
          --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f migrations/dev/configmap.yaml

    - name: Delete previous migration job if exists
      run: kubectl delete job mysql-migration -n dev --ignore-not-found=true

    - name: Run migration job
      run: |
        kubectl apply -f migrations/dev/migration-job.yaml
        kubectl wait --for=condition=complete job/mysql-migration -n dev --timeout=300s

    - name: Print migration logs
      run: kubectl logs job/mysql-migration -n dev
